sources:
- archive: syslog_protocol-0.9.2.gem
  archive_sha512sum: cf94f495e57767517abfd8552baa09b284e016b03631871f72eb4aa5636958fea524c4f53c7d19b1b4fd7e1ee0f0c17297ce8a86d2b0e8efc3737018b2701646
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Syslog protocol parser and generator '
      home_page: https://rubygems.org/gems/syslog_protocol/versions/0.9.2
      license_concluded: MIT
      license_declared: MIT
      short_summary: Syslog Protocol
      supplier: 'Organization: Broadcom, Inc.'
