sources:
- archive: vcversioner-2.16.0.0.tar.gz
  archive_sha512sum: e4e34693aa813e57991eca01d20102bd2e939b536461e2e9e063ac0e3558580e57d7e8d5e08d010690b3c901c97e53f187f20b48520b333eb492ec33e85757d8
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Elevator pitch: you can write a setup.py with no version
        information specified, and vcversioner will find a recent, properly-formatted
        VCS tag and extract a version from it. '
      home_page: https://github.com/habnabit/vcversioner
      license_concluded: ISC
      license_declared: ISC
      short_summary: Python version extractor
      supplier: 'Organization: Broadcom, Inc.'
