sources:
- archive: dbus-python-1.3.2.tar.gz
  archive_sha512sum: 9b2885c9c2914142c72487f766b1cdd28a255d9f5a87eaf8f4eb420c6e096a77f210ac5a4fac9843c6531974872880cc28b7e45940e198856e984dcc0715519a
  skip_validation: true
  spdx:
    package:
      detailed_description: 'D-Bus python bindings for use with python programs. '
      home_page: http://www.freedesktop.org/wiki/Software/DBusBindings/
      license_concluded: FSFAP AND (AFL-2.1 OR GPL-2.0-or-later) AND (AFL-2.1 AND
        GPL-2.0-or-later) AND (AFL-2.1 OR GPL-2.0-or-later) AND GPL-3.0-or-later WITH
        Autoconf-exception-2.0 AND FSFULLRWD AND GPL-2.0-or-later WITH Autoconf-exception-generic
        AND GPL-3.0-only AND X11 AND GPL-2.0-or-later WITH Libtool-exception AND GPL-2.0-only
        AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND AFL-2.1 AND FSFUL
        AND GPL-2.0-or-later AND MIT AND GPL-3.0-or-later AND FSFULLR
      license_declared: FSFAP AND (AFL-2.1 OR GPL-2.0-or-later) AND (AFL-2.1 AND GPL-2.0-or-later)
        AND (AFL-2.1 OR GPL-2.0-or-later) AND GPL-3.0-or-later WITH Autoconf-exception-2.0
        AND FSFULLRWD AND GPL-2.0-or-later WITH Autoconf-exception-generic AND GPL-3.0-only
        AND X11 AND GPL-2.0-or-later WITH Libtool-exception AND GPL-2.0-only AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND AFL-2.1 AND FSFUL AND GPL-2.0-or-later
        AND MIT AND GPL-3.0-or-later AND FSFULLR
      short_summary: Python bindings for D-Bus
      supplier: 'Organization: Broadcom, Inc.'
