sources:
- archive: XML-Parser-2.46.tar.gz
  archive_sha512sum: c4609495cc5ca34952f61876a690ef76d42eee6689d1bedb8036c9eab918525ec5213f1639c7178c029ee0f8765a2ca5eb0197f6e39b8be6d5dbc3f3c1d0b389
  skip_validation: true
  spdx:
    package:
      detailed_description: 'The XML::Parser module is a Perl extension interface
        to James Clark''s XML parser, expat '
      home_page: http://search.cpan.org/~toddr/XML-Parser-2.46/
      license_concluded: Ruby
      license_declared: Ruby
      short_summary: XML-Parser perl module
      supplier: 'Organization: Broadcom, Inc.'
