sources:
- archive: xml-security-c-2.0.4.tar.bz2
  archive_sha512sum: a27d76686cc97f7ac60101c562b04b1091b026ac71ed557284cfd91f5b722db97bdc04d7cab65f932c4e34022d15911b0a7cbc7e4c7f3ec1a5860c3f298e1c66
  skip_validation: true
  spdx:
    package:
      detailed_description: 'XML-Security-C is the C++ XML Signature and Encryption
        library from the Apache Software Foundation. It is used for all XML Signature
        and Encryption processing in OpenSAML and Shibboleth. '
      home_page: https://santuario.apache.org/cindex.html
      license_concluded: FSFULLRWD AND FSFULLR AND X11 AND FSFAP AND Apache-2.0 AND
        GPL-2.0-or-later WITH Libtool-exception AND GPL-2.0-or-later WITH Autoconf-exception-macro
        AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-3.0-or-later WITH
        Libtool-exception AND FSFUL AND GPL-3.0-or-later AND GPL-3.0-or-later WITH
        Autoconf-exception-generic-3.0 AND GPL-2.0-or-later WITH Autoconf-exception-generic
      license_declared: FSFULLRWD AND FSFULLR AND X11 AND FSFAP AND Apache-2.0 AND
        GPL-2.0-or-later WITH Libtool-exception AND GPL-2.0-or-later WITH Autoconf-exception-macro
        AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND GPL-3.0-or-later WITH
        Libtool-exception AND FSFUL AND GPL-3.0-or-later AND GPL-3.0-or-later WITH
        Autoconf-exception-generic-3.0 AND GPL-2.0-or-later WITH Autoconf-exception-generic
      short_summary: C++ XML Signature and Encryption library.
      supplier: 'Organization: Broadcom, Inc.'
