sources:
- archive: apache-tomcat-10.1.34-src.tar.gz
  archive_sha512sum: 0124d92eb1d184bdce1a50d5934958a0c796460a7157a8622aeee2b21060f5377198939a0260285bcdaa25cea42b880cb97575469a63f7b33ec22d532927e6ca
  skip_validation: true
  spdx:
    package:
      detailed_description: 'The Apache Tomcat package contains binaries for the Apache
        Tomcat servlet container. '
      home_page: http://tomcat.apache.org
      license_concluded: CPL-1.0 AND Apache-2.0 AND (Apache-2.0 AND CDDL-1.0) AND
        CC0-1.0 AND Zlib AND EPL-2.0 AND bzip2-1.0.6 AND LGPL-2.0-or-later AND (CDDL-1.0
        OR GPL-2.0-only WITH Classpath-exception-2.0) AND EPL-1.0 AND CDDL-1.0 AND
        (EPL-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0) AND GPL-2.0-only
      license_declared: CPL-1.0 AND Apache-2.0 AND (Apache-2.0 AND CDDL-1.0) AND CC0-1.0
        AND Zlib AND EPL-2.0 AND bzip2-1.0.6 AND LGPL-2.0-or-later AND (CDDL-1.0 OR
        GPL-2.0-only WITH Classpath-exception-2.0) AND EPL-1.0 AND CDDL-1.0 AND (EPL-2.0
        OR GPL-2.0-only WITH Classpath-exception-2.0) AND GPL-2.0-only
      short_summary: Apache Tomcat 10.1
      supplier: 'Organization: Broadcom, Inc.'
- archive: apache-tomcat-9.0.98-src.tar.gz
  archive_sha512sum: eb380dae515a259d23d5311d0b96b8ef5068c0d8d72da215410e5475582d2ff82182b7331e0d197eb993d8014a99ea40290154a343e961a07ed02be6894759cc
  skip_validation: true
  spdx:
    package:
      detailed_description: The Apache Tomcat package provides the Apache Tomcat servlet
        container.
      home_page: http://tomcat.apache.org
      license_concluded: bzip2-1.0.6 AND EPL-1.0 AND (Apache-2.0 AND CDDL-1.0) AND
        Apache-2.0 AND (CDDL-1.0 OR GPL-2.0-only WITH Classpath-exception-2.0) AND
        CPL-1.0 AND LGPL-2.0-or-later AND CDDL-1.0 AND CC0-1.0 AND GPL-2.0-only AND
        Zlib
      license_declared: bzip2-1.0.6 AND EPL-1.0 AND (Apache-2.0 AND CDDL-1.0) AND
        Apache-2.0 AND (CDDL-1.0 OR GPL-2.0-only WITH Classpath-exception-2.0) AND
        CPL-1.0 AND LGPL-2.0-or-later AND CDDL-1.0 AND CC0-1.0 AND GPL-2.0-only AND
        Zlib
      short_summary: Apache Tomcat 9
      supplier: 'Organization: Broadcom, Inc.'
- archive: base-for-apache-tomcat-10.1.34.tar.gz
  archive_sha512sum: c764124c351e8b22a7bd65026d1039a27027adfe651b97757ea4e07c3f81779557cfbaab741866dbf37942be5b302c92216f905e31c2aae27594aa590fc9f446
  skip_validation: true
  spdx:
    package:
      detailed_description: base-for-apache-tomcat is a cached -Dbase.path folder
        after apache-tomcat build
      home_page: https://github.com/vmware/photon
      license_concluded: OpenSSL-standalone AND BSD-3-Clause AND CPL-1.0 AND BSD-2-Clause-Views
        AND Zlib AND FSFUL AND (Apache-2.0 OR EPL-2.0) AND (Apache-2.0 OR EPL-2.0)
        AND bzip2-1.0.6 AND GPL-3.0-or-later AND FSFULLRWD AND GPL-2.0-or-later AND
        EPL-2.0 AND GPL-2.0-or-later WITH Libtool-exception AND LGPL-2.1-only AND
        GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND GPL-3.0-only AND
        X11 AND MIT AND CDDL-1.0 AND GPL-3.0-or-later WITH Libtool-exception AND GPL-2.0-only
        AND BSD-2-Clause AND LGPL-2.1-or-later AND FSFULLR AND Apache-2.0 AND EPL-1.0
        AND SSLeay-standalone AND MPL-2.0
      license_declared: OpenSSL-standalone AND BSD-3-Clause AND CPL-1.0 AND BSD-2-Clause-Views
        AND Zlib AND FSFUL AND (Apache-2.0 OR EPL-2.0) AND (Apache-2.0 OR EPL-2.0)
        AND bzip2-1.0.6 AND GPL-3.0-or-later AND FSFULLRWD AND GPL-2.0-or-later AND
        EPL-2.0 AND GPL-2.0-or-later WITH Libtool-exception AND LGPL-2.1-only AND
        GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND GPL-3.0-only AND
        X11 AND MIT AND CDDL-1.0 AND GPL-3.0-or-later WITH Libtool-exception AND GPL-2.0-only
        AND BSD-2-Clause AND LGPL-2.1-or-later AND FSFULLR AND Apache-2.0 AND EPL-1.0
        AND SSLeay-standalone AND MPL-2.0
      short_summary: Cached -Dbase.path folder of apache-tomcat build
      supplier: 'Organization: Broadcom, Inc.'
- archive: base-for-apache-tomcat-9.0.98.tar.gz
  archive_sha512sum: c6e718f37fc71247459e3932313931ef53ec1c8276a70b791ac9982702dcfae17c2670ab235c9b2cb905e6b9c71c6c3b6653f8bc827f8aaae1a8f9603eed2b07
  skip_validation: true
  spdx:
    package:
      detailed_description: base-for-apache-tomcat is a cached -Dbase.path folder
        after apache-tomcat build
      home_page: https://github.com/vmware/photon
      license_concluded: MPL-2.0 AND OpenSSL-standalone AND GPL-2.0-only AND BSD-3-Clause
        AND FSFUL AND BSD-2-Clause AND GPL-2.0-or-later AND GPL-3.0-only AND BSD-2-Clause-Views
        AND (Apache-2.0 OR EPL-2.0) AND Zlib AND CDDL-1.0 AND EPL-2.0 AND MIT AND
        SSLeay-standalone AND bzip2-1.0.6 AND GPL-3.0-or-later AND (Apache-2.0 OR
        EPL-2.0) AND LGPL-2.1-or-later AND EPL-1.0 AND CPL-1.0 AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND LGPL-2.1-only AND Apache-2.0
      license_declared: MPL-2.0 AND OpenSSL-standalone AND GPL-2.0-only AND BSD-3-Clause
        AND FSFUL AND BSD-2-Clause AND GPL-2.0-or-later AND GPL-3.0-only AND BSD-2-Clause-Views
        AND (Apache-2.0 OR EPL-2.0) AND Zlib AND CDDL-1.0 AND EPL-2.0 AND MIT AND
        SSLeay-standalone AND bzip2-1.0.6 AND GPL-3.0-or-later AND (Apache-2.0 OR
        EPL-2.0) AND LGPL-2.1-or-later AND EPL-1.0 AND CPL-1.0 AND GPL-3.0-or-later
        WITH Autoconf-exception-generic-3.0 AND LGPL-2.1-only AND Apache-2.0
      short_summary: Cached -Dbase.path folder of apache-tomcat build
      supplier: 'Organization: Broadcom, Inc.'
