sources:
- archive: cmake-3.25.2.tar.gz
  archive_sha512sum: 20146d06a1722c36249192944a58e4780aad334d2bc5ce2a3d8c4f24656630c5b71ca0ae7ed53587e3d46f488bd773452fa60c3fc7045fe54db2dbc6ffd86390
  skip_validation: true
  spdx:
    package:
      detailed_description: 'CMake is an extensible, open-source system that manages
        the build process in an operating system and in a compiler-independent manner. '
      home_page: http://www.cmake.org
      license_concluded: LGPL-3.0-only AND GPL-3.0-or-later AND Spencer-86 AND bzip2-1.0.6
        AND BSD-2-Clause-Views AND PostgreSQL AND GPL-3.0-or-later WITH Bison-exception-2.2
        AND Zlib AND BSD-3-Clause AND LGPL-2.1-only AND BSL-1.0 AND ISC AND X11-distribute-modifications-variant
        AND 0BSD AND MIT AND GPL-2.0-only AND GPL-2.0-or-later AND LGPL-2.1-or-later
        AND (BSD-3-Clause OR GPL-2.0-only) AND CC0-1.0 AND BSD-2-Clause AND curl AND
        Apache-2.0 AND GPL-1.0-or-later AND LGPL-2.0-only AND GPL-3.0-only AND (curl
        AND ISC)
      license_declared: LGPL-3.0-only AND GPL-3.0-or-later AND Spencer-86 AND bzip2-1.0.6
        AND BSD-2-Clause-Views AND PostgreSQL AND GPL-3.0-or-later WITH Bison-exception-2.2
        AND Zlib AND BSD-3-Clause AND LGPL-2.1-only AND BSL-1.0 AND ISC AND X11-distribute-modifications-variant
        AND 0BSD AND MIT AND GPL-2.0-only AND GPL-2.0-or-later AND LGPL-2.1-or-later
        AND (BSD-3-Clause OR GPL-2.0-only) AND CC0-1.0 AND BSD-2-Clause AND curl AND
        Apache-2.0 AND GPL-1.0-or-later AND LGPL-2.0-only AND GPL-3.0-only AND (curl
        AND ISC)
      short_summary: Cross-platform make system
      supplier: 'Organization: Broadcom, Inc.'
