sources:
- archive: http-5.1.0.gem
  archive_sha512sum: b99da5318da54e7b64abd48df0b68cde9a02e1ae92b51fc43302e3dea28ba9672e2b7a25e31c342235835e16b2e1b98c94b6d4efa7916a0aa99258fc8290260f
  skip_validation: true
  spdx:
    package:
      detailed_description: 'An easy-to-use client library for making requests from
        Ruby. It uses a simple method chaining system for building requests, similar
        to Python''s Requests. '
      home_page: https://rubygems.org/gems/http/versions/5.1.0
      license_concluded: MIT
      license_declared: MIT
      short_summary: An easy-to-use client library for making requests from Ruby.
      supplier: 'Organization: Broadcom, Inc.'
