sources:
- archive: docker-cli-27.3.1.tar.gz
  archive_sha512sum: 6e80e94a0e9e16aaf2b19bc97c99ead39184745f601aea94e47c066a19b6436850d5269962e0802e9f7fa9f7dcb357ec0756c9466afa2c0a6ae239d61ef15961
  skip_validation: true
  spdx:
    package:
      detailed_description: Docker CLI
      home_page: https://github.com/docker/cli
      license_concluded: BSD-3-Clause AND BSD-2-Clause AND (BSD-3-Clause AND Apache-2.0)
        AND GPL-1.0-or-later AND CC-BY-SA-4.0 AND Apache-2.0 AND MIT
      license_declared: BSD-3-Clause AND BSD-2-Clause AND (BSD-3-Clause AND Apache-2.0)
        AND GPL-1.0-or-later AND CC-BY-SA-4.0 AND Apache-2.0 AND MIT
      short_summary: Docker CLI
      supplier: 'Organization: Broadcom, Inc.'
- archive: libnetwork-64b7a45.tar.gz
  archive_sha512sum: e4102a20d2ff681de7bc52381d473c6f6b13d1d59fb14a749e8e3ceda439a74dd7cf2046a2042019c646269173b55d4e78140fe5e8c59d913895a35d4a5f40a4
  skip_validation: true
  spdx:
    package:
      detailed_description: Libnetwork provides a native Go implementation for connecting
        containers
      home_page: https://github.com/docker/libnetwork
      license_concluded: MIT AND CC-BY-SA-4.0 AND Apache-2.0 AND BSD-2-Clause AND
        BSD-3-Clause AND MPL-2.0
      license_declared: MIT AND CC-BY-SA-4.0 AND Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause
        AND MPL-2.0
      short_summary: networking for containers
      supplier: 'Organization: Broadcom, Inc.'
- archive: moby-27.3.1.tar.gz
  archive_sha512sum: 0fddcc8314eed2e7b131af78f1fa01292cfc4fcb7fd0af94b79d5435349ab54a21b0a78cffbf29dd4c58747d8bcd1f47473cc5f5ab2596e133828b2e6540d172
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Docker is an open source project to build, ship and run
        any application as a lightweight container. '
      home_page: http://docs.docker.com
      license_concluded: BSD-2-Clause AND GPL-1.0-or-later AND MIT AND CC-BY-4.0 AND
        MPL-2.0 AND GPL-2.0-only AND CC0-1.0 AND ISC AND (Apache-2.0 OR GPL-2.0-or-later)
        AND BSD-3-Clause AND Apache-2.0 AND (Apache-2.0 OR GPL-2.0-or-later) AND CC-BY-SA-4.0
        AND (BSD-3-Clause AND Apache-2.0)
      license_declared: BSD-2-Clause AND GPL-1.0-or-later AND MIT AND CC-BY-4.0 AND
        MPL-2.0 AND GPL-2.0-only AND CC0-1.0 AND ISC AND (Apache-2.0 OR GPL-2.0-or-later)
        AND BSD-3-Clause AND Apache-2.0 AND (Apache-2.0 OR GPL-2.0-or-later) AND CC-BY-SA-4.0
        AND (BSD-3-Clause AND Apache-2.0)
      short_summary: Docker
      supplier: 'Organization: Broadcom, Inc.'
- archive: tini-0.19.0.tar.gz
  archive_sha512sum: 3591a6db54b8f35c30eafc6bbf8903926c382fd7fe2926faea5d95c7b562130b5264228df550f2ad83581856fd5291cf4aab44ee078aef3270c74be70886055c
  skip_validation: true
  spdx:
    package:
      detailed_description: A tiny but valid init for containers
      home_page: https://github.com/krallin/tini
      license_concluded: MIT
      license_declared: MIT
      short_summary: A tiny but valid init for containers
      supplier: 'Organization: Broadcom, Inc.'
