sources:
- archive: backports.ssl_match_hostname-3.7.0.1.tar.gz
  archive_sha512sum: 9048ed093dc8a166a80d16a9aa0e06d36ea43ce7d324818608d25b1ef5057b1c66dd3514f9b35ab13bc60b2e5a3de29e690607e928fac2c9df16506759bd14dd
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Backported python ssl_match_hostname feature '
      home_page: https://pypi.org/project/backports.ssl_match_hostname
      license_concluded: Python-2.0
      license_declared: Python-2.0
      short_summary: Backported python ssl_match_hostname
      supplier: 'Organization: Broadcom, Inc.'
