sources:
- archive: createrepo_c-0.20.1.tar.gz
  archive_sha512sum: 54a2cc7c7cd3f3b9a0c23cd8c136ae1331e7fa7cc995189088e7e6f2276c78b2b84e21c2a2b93f4528b5e9e4018dd6525262c8aaba3bc8a1412a51dfafd101f7
  skip_validation: true
  spdx:
    package:
      detailed_description: 'C implementation of the createrepo. '
      home_page: https://github.com/rpm-software-management/createrepo_c
      license_concluded: CDDL-1.0 AND Apache-1.1 AND MIT AND GPL-2.0-or-later AND
        GPL-3.0-only AND EPL-1.0 AND GPL-1.0-or-later AND LGPL-2.0-only AND Apache-2.0
        AND LGPL-3.0-only AND LGPL-2.1-or-later AND (GPL-2.0-or-later OR LGPL-2.0-or-later)
        AND MPL-2.0 AND LGPL-3.0-or-later AND HaskellReport AND GPL-2.0-only AND LGPL-2.0-or-later
        AND GPL-3.0-or-later
      license_declared: CDDL-1.0 AND Apache-1.1 AND MIT AND GPL-2.0-or-later AND GPL-3.0-only
        AND EPL-1.0 AND GPL-1.0-or-later AND LGPL-2.0-only AND Apache-2.0 AND LGPL-3.0-only
        AND LGPL-2.1-or-later AND (GPL-2.0-or-later OR LGPL-2.0-or-later) AND MPL-2.0
        AND LGPL-3.0-or-later AND HaskellReport AND GPL-2.0-only AND LGPL-2.0-or-later
        AND GPL-3.0-or-later
      short_summary: Creates a common metadata repository
      supplier: 'Organization: Broadcom, Inc.'
